version: "3"
services: 
  manager:
    build: 
      context: "./manager"
      dockerfile: "dockerfile"
    depends_on:
      - "db"
    environment:
      CSV_FILENAME: "data"
    ports: 
      - 2000:5432
  db : 
    image: "postgres"
    
